version: '3.8'

services:
  spark-master:
    image: bitnami/spark:3.4
    platform: linux/arm64
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - HOME=/tmp
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./data:/tmp/data
      - ./app:/opt/spark-apps

  spark-worker-1:
    image: bitnami/spark:3.4
    platform: linux/arm64
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    volumes:
      - ./data:/tmp/data
      - ./app:/opt/spark-apps

